language: node_js
node_js:
  - 11.6.0
cache: npm

install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_token
  on:
    branch: master
